### ISSUE TITLE
Decide on approach

### ISSUE THREAD

**Issue by rowanwins** [rowanwins/turf-overlap#1]
cc @tcql and @morganherlocker

The idea was originally based on a single input poly and comparing it to a collection of polys. I've expanded it a bit to include multiple input polys but its still very polygon focussed.

Need to decide
- should this module cater for various input feature types? (eg point, line, poly, or featurecollection of polys only) , if so how would it best be structured...
- same for the featurecollection being scanned and returned?

Other things
- is the current approach the best (BBOX ->line intersection ->point-in-poly)? It's what I've cobbled together and seems to work well but happy for other suggestions

**Comment by rowanwins** [comment]
I wonder if I can use something like node-async for this module? Given that I essentially want to run the same operation lots of times is this a good fit - hmm probably need to understand this better...

https://github.com/caolan/async

**Comment by morganherlocker** [comment]
> I wonder if I can use something like node-async for this module? 

All turf functions are CPU-bound and synchronous (no async callbacks). A `for` loop is all you need.
